networks:
  proxy:
    name: backbone_proxy
    external: true
  database:
    name: backbone_database
    external: true
  application:
    external: false

services:
  orchestra:
    restart: unless-stopped
    image: ezka77/xen-orchestra-ce:latest
    container_name: xo_server
    depends_on:
      - redis
    labels:
      - traefik.enable=true
      - traefik.http.routers.xoa.tls=true
      - traefik.http.routers.xoa.rule=Host("${APPLICATION_FQDN}")
      - traefik.http.routers.xoa.service=xoa-service
      - traefik.http.services.xoa-service.loadbalancer.server.port=80
    environment:
      DEBUG=xo: main
      NODE_ENV: production
      XOA_PLAN: 5
      XO_HTTP_REDIRECTTOHTTPS: false
      XO_HTTP_LISTEN_PORT: 80
      XO_HTTPS_LISTEN_PORT: 443
      XO_HTTPS_LISTEN_AUTOCERT: true
    privileged: true
    # SYS_ADMIN should be enough capability to use NFS mount
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    volumes:
      - ./xo-data:/storage
    networks:
      - proxy
      - application
    logging: &default_logging
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "2"

  redis:
    restart: unless-stopped
    container_name: XO_redis
    image: redis:alpine
    command: redis-server --appendonly yes
    volumes:
      - ./redis-data:/data
    networks:
      - application
    logging:
      <<: *default_logging
